keyconfig_version = (2, 92, 15)
keyconfig_data = \
[("3D View",
  {"space_type": 'VIEW_3D', "region_type": 'WINDOW'},
  {"items":
   [("object.cablerator_helper_remove_hook",
     {"type": 'NONE', "value": 'PRESS'},
     {    "active":False,
      },
     ),
    ("object.cablerator_helper_apply_hook",
     {"type": 'NONE', "value": 'PRESS'},
     {    "active":False,
      },
     ),
    ("object.cablerator_helper_single_vert",
     {"type": 'NONE', "value": 'PRESS'},
     {    "active":False,
      },
     ),
    ("object.cablerator_helper_add_circle",
     {"type": 'NONE', "value": 'PRESS'},
     {    "active":False,
      },
     ),
    ("object.cablerator_helper_find_profile",
     {"type": 'NONE', "value": 'PRESS'},
     {    "active":False,
      },
     ),
    ("object.cableratorsplitrecable",
     {"type": 'NONE', "value": 'PRESS'},
     {    "active":False,
      },
     ),
    ("object.cableratorsplit",
     {"type": 'NONE', "value": 'PRESS'},
     {    "active":False,
      },
     ),
    ("object.cablerator_geocable",
     {"type": 'NONE', "value": 'PRESS'},
     {    "active":False,
      },
     ),
    ("object.cablerator_segment",
     {"type": 'NONE', "value": 'PRESS'},
     {    "active":False,
      },
     ),
    ("object.cablerator_connector",
     {"type": 'NONE', "value": 'PRESS'},
     {    "active":False,
      },
     ),
    ("object.cableratorconnect",
     {"type": 'NONE', "value": 'PRESS'},
     {    "active":False,
      },
     ),
    ("object.cablerator_edit_cable",
     {"type": 'NONE', "value": 'PRESS'},
     {    "active":False,
      },
     ),
    ("object.cablerator_create_cable_from_selected",
     {"type": 'NONE', "value": 'PRESS'},
     {    "active":False,
      },
     ),
    ("object.cablerator_create_cable_from_edge",
     {"type": 'NONE', "value": 'PRESS'},
     {    "active":False,
      },
     ),
    ("object.cableratordraw",
     {"type": 'NONE', "value": 'PRESS'},
     {    "active":False,
      },
     ),
    ("object.cablerator",
     {"type": 'NONE', "value": 'PRESS'},
     {    "active":False,
      },
     ),
    ("wm.call_menu",
     {"type": 'C', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("name", 'VIEW3D_MT_cablerator'),
       ],
      },
     ),
    ("bc.tool_activate", {"type": 'W', "value": 'PRESS', "alt": True}, None),
    ("hardflow.topbar_activate", {"type": 'W', "value": 'PRESS', "shift": True, "alt": True}, None),
    ("hops.adjust_logo", {"type": 'L', "value": 'PRESS', "shift": True, "ctrl": True, "alt": True}, None),
    ("hops.tilde_remap",
     {"type": 'ACCENT_GRAVE', "value": 'PRESS'},
     {    "active":False,
      },
     ),
    ("hops.bevel_helper", {"type": 'B', "value": 'PRESS', "shift": True, "alt": True}, None),
    ("hops.bev_multi", {"type": 'B', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("hops.mirror_gizmo", {"type": 'X', "value": 'PRESS', "alt": True}, None),
    ("wm.call_menu",
     {"type": 'V', "value": 'PRESS', "alt": True},
     {"properties":
      [("name", 'HOPS_MT_ViewportSubmenu'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'M', "value": 'PRESS', "alt": True},
     {"properties":
      [("name", 'HOPS_MT_MaterialListMenu'),
       ],
      },
     ),
    ("hops.helper", {"type": 'ACCENT_GRAVE', "value": 'PRESS', "ctrl": True}, None),
    ("hops.pref_helper", {"type": 'K', "value": 'PRESS', "ctrl": True}, None),
    ("wm.call_menu",
     {"type": 'Q', "value": 'PRESS'},
     {"properties":
      [("name", 'HOPS_MT_MainMenu'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'Q', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'HOPS_MT_MainPie'),
       ],
      },
     ),
    ("object.cablerator_helper_remove_hook",
     {"type": 'NONE', "value": 'PRESS'},
     {    "active":False,
      },
     ),
    ("object.cablerator_helper_apply_hook",
     {"type": 'NONE', "value": 'PRESS'},
     {    "active":False,
      },
     ),
    ("object.cablerator_helper_single_vert",
     {"type": 'NONE', "value": 'PRESS'},
     {    "active":False,
      },
     ),
    ("object.cablerator_helper_add_circle",
     {"type": 'NONE', "value": 'PRESS'},
     {    "active":False,
      },
     ),
    ("object.cablerator_helper_find_profile",
     {"type": 'NONE', "value": 'PRESS'},
     {    "active":False,
      },
     ),
    ("object.cableratorsplitrecable",
     {"type": 'NONE', "value": 'PRESS'},
     {    "active":False,
      },
     ),
    ("object.cableratorsplit",
     {"type": 'NONE', "value": 'PRESS'},
     {    "active":False,
      },
     ),
    ("object.cablerator_geocable",
     {"type": 'NONE', "value": 'PRESS'},
     {    "active":False,
      },
     ),
    ("object.cablerator_segment",
     {"type": 'NONE', "value": 'PRESS'},
     {    "active":False,
      },
     ),
    ("object.cablerator_connector",
     {"type": 'NONE', "value": 'PRESS'},
     {    "active":False,
      },
     ),
    ("object.cableratorconnect",
     {"type": 'NONE', "value": 'PRESS'},
     {    "active":False,
      },
     ),
    ("object.cablerator_edit_cable",
     {"type": 'NONE', "value": 'PRESS'},
     {    "active":False,
      },
     ),
    ("object.cablerator_create_cable_from_selected",
     {"type": 'NONE', "value": 'PRESS'},
     {    "active":False,
      },
     ),
    ("object.cablerator_create_cable_from_edge",
     {"type": 'NONE', "value": 'PRESS'},
     {    "active":False,
      },
     ),
    ("object.cableratordraw",
     {"type": 'NONE', "value": 'PRESS'},
     {    "active":False,
      },
     ),
    ("object.cablerator",
     {"type": 'NONE', "value": 'PRESS'},
     {    "active":False,
      },
     ),
    ("wm.call_menu",
     {"type": 'C', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("name", 'VIEW3D_MT_cablerator'),
       ],
      },
     ),
    ("bc.tool_activate", {"type": 'W', "value": 'PRESS', "alt": True}, None),
    ("hardflow.topbar_activate", {"type": 'W', "value": 'PRESS', "shift": True, "alt": True}, None),
    ("hops.adjust_logo", {"type": 'L', "value": 'PRESS', "shift": True, "ctrl": True, "alt": True}, None),
    ("hops.tilde_remap",
     {"type": 'ACCENT_GRAVE', "value": 'PRESS'},
     {    "active":False,
      },
     ),
    ("hops.bevel_helper", {"type": 'B', "value": 'PRESS', "shift": True, "alt": True}, None),
    ("hops.bev_multi", {"type": 'B', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("hops.mirror_gizmo", {"type": 'X', "value": 'PRESS', "alt": True}, None),
    ("wm.call_menu",
     {"type": 'V', "value": 'PRESS', "alt": True},
     {"properties":
      [("name", 'HOPS_MT_ViewportSubmenu'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'M', "value": 'PRESS', "alt": True},
     {"properties":
      [("name", 'HOPS_MT_MaterialListMenu'),
       ],
      },
     ),
    ("hops.helper", {"type": 'ACCENT_GRAVE', "value": 'PRESS', "ctrl": True}, None),
    ("hops.pref_helper", {"type": 'K', "value": 'PRESS', "ctrl": True}, None),
    ("wm.call_menu",
     {"type": 'Q', "value": 'PRESS'},
     {"properties":
      [("name", 'HOPS_MT_MainMenu'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'Q', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'HOPS_MT_MainPie'),
       ],
      },
     ),
    ("view3d.cursor3d", {"type": 'RIGHTMOUSE', "value": 'PRESS', "shift": True}, None),
    ("transform.translate",
     {"type": 'EVT_TWEAK_R', "value": 'ANY', "shift": True},
     {"properties":
      [("cursor_transform", True),
       ("release_confirm", True),
       ],
      },
     ),
    ("view3d.localview", {"type": 'NUMPAD_SLASH', "value": 'PRESS'}, None),
    ("view3d.localview", {"type": 'SLASH', "value": 'PRESS'}, None),
    ("view3d.localview", {"type": 'MOUSESMARTZOOM', "value": 'ANY'}, None),
    ("view3d.localview_remove_from", {"type": 'M', "value": 'PRESS'}, None),
    ("view3d.rotate", {"type": 'MOUSEROTATE', "value": 'ANY'}, None),
    ("view3d.rotate", {"type": 'MIDDLEMOUSE', "value": 'PRESS'}, None),
    ("view3d.move", {"type": 'MIDDLEMOUSE', "value": 'PRESS', "shift": True}, None),
    ("view3d.rotate", {"type": 'TRACKPADPAN', "value": 'ANY'}, None),
    ("view3d.move", {"type": 'TRACKPADPAN', "value": 'ANY', "shift": True}, None),
    ("view3d.zoom", {"type": 'MIDDLEMOUSE', "value": 'PRESS', "ctrl": True}, None),
    ("view3d.dolly", {"type": 'MIDDLEMOUSE', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("view3d.view_selected",
     {"type": 'BUTTON5MOUSE', "value": 'PRESS'},
     {"properties":
      [("use_all_regions", True),
       ],
      },
     ),
    ("view3d.smoothview", {"type": 'TIMER1', "value": 'ANY', "any": True}, None),
    ("view3d.zoom", {"type": 'TRACKPADZOOM', "value": 'ANY'}, None),
    ("view3d.zoom", {"type": 'TRACKPADPAN', "value": 'ANY', "ctrl": True}, None),
    ("view3d.zoom",
     {"type": 'NUMPAD_PLUS', "value": 'PRESS', "repeat": True},
     {"properties":
      [("delta", 1),
       ],
      },
     ),
    ("view3d.zoom",
     {"type": 'NUMPAD_MINUS', "value": 'PRESS', "repeat": True},
     {"properties":
      [("delta", -1),
       ],
      },
     ),
    ("view3d.zoom",
     {"type": 'EQUAL', "value": 'PRESS', "ctrl": True, "repeat": True},
     {"properties":
      [("delta", 1),
       ],
      },
     ),
    ("view3d.zoom",
     {"type": 'MINUS', "value": 'PRESS', "ctrl": True, "repeat": True},
     {"properties":
      [("delta", -1),
       ],
      },
     ),
    ("view3d.zoom",
     {"type": 'WHEELINMOUSE', "value": 'PRESS'},
     {"properties":
      [("delta", 1),
       ],
      },
     ),
    ("view3d.zoom",
     {"type": 'WHEELOUTMOUSE', "value": 'PRESS'},
     {"properties":
      [("delta", -1),
       ],
      },
     ),
    ("view3d.dolly",
     {"type": 'NUMPAD_PLUS', "value": 'PRESS', "shift": True, "repeat": True},
     {"properties":
      [("delta", 1),
       ],
      },
     ),
    ("view3d.dolly",
     {"type": 'NUMPAD_MINUS', "value": 'PRESS', "shift": True, "repeat": True},
     {"properties":
      [("delta", -1),
       ],
      },
     ),
    ("view3d.dolly",
     {"type": 'EQUAL', "value": 'PRESS', "shift": True, "ctrl": True, "repeat": True},
     {"properties":
      [("delta", 1),
       ],
      },
     ),
    ("view3d.dolly",
     {"type": 'MINUS', "value": 'PRESS', "shift": True, "ctrl": True, "repeat": True},
     {"properties":
      [("delta", -1),
       ],
      },
     ),
    ("view3d.view_center_camera", {"type": 'HOME', "value": 'PRESS'}, None),
    ("view3d.view_center_lock", {"type": 'HOME', "value": 'PRESS'}, None),
    ("view3d.view_all",
     {"type": 'HOME', "value": 'PRESS'},
     {"properties":
      [("center", False),
       ],
      },
     ),
    ("view3d.view_all",
     {"type": 'HOME', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("use_all_regions", True),
       ("center", False),
       ],
      },
     ),
    ("view3d.view_all",
     {"type": 'C', "value": 'PRESS', "shift": True},
     {"properties":
      [("center", True),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'ACCENT_GRAVE', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_view_pie'),
       ],
      },
     ),
    ("view3d.navigate", {"type": 'NUMPAD_8', "value": 'PRESS'}, None),
    ("view3d.view_camera", {"type": 'NUMPAD_0', "value": 'PRESS'}, None),
    ("view3d.view_axis",
     {"type": 'NUMPAD_1', "value": 'PRESS'},
     {"properties":
      [("type", 'FRONT'),
       ],
      },
     ),
    ("view3d.view_orbit",
     {"type": 'NUMPAD_5', "value": 'PRESS', "repeat": True},
     {"properties":
      [("type", 'ORBITDOWN'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_2', "value": 'PRESS'},
     {"properties":
      [("type", 'RIGHT'),
       ("align_active", False),
       ("relative", False),
       ],
      },
     ),
    ("view3d.view_orbit",
     {"type": 'NUMPAD_6', "value": 'PRESS', "repeat": True},
     {"properties":
      [("type", 'ORBITLEFT'),
       ],
      },
     ),
    ("view3d.view_persportho", {"type": 'NUMPAD_5', "value": 'PRESS'}, None),
    ("view3d.view_orbit",
     {"type": 'NUMPAD_7', "value": 'PRESS', "repeat": True},
     {"properties":
      [("type", 'ORBITRIGHT'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_3', "value": 'PRESS'},
     {"properties":
      [("type", 'TOP'),
       ],
      },
     ),
    ("view3d.view_orbit",
     {"type": 'NUMPAD_4', "value": 'PRESS', "repeat": True},
     {"properties":
      [("type", 'ORBITUP'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_1', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("type", 'BACK'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_2', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("type", 'LEFT'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NUMPAD_3', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("type", 'BOTTOM'),
       ],
      },
     ),
    ("view3d.view_pan",
     {"type": 'NUMPAD_5', "value": 'PRESS', "ctrl": True, "repeat": True},
     {"properties":
      [("type", 'PANDOWN'),
       ],
      },
     ),
    ("view3d.view_pan",
     {"type": 'NUMPAD_6', "value": 'PRESS', "ctrl": True, "repeat": True},
     {"properties":
      [("type", 'PANLEFT'),
       ],
      },
     ),
    ("view3d.view_pan",
     {"type": 'NUMPAD_7', "value": 'PRESS', "ctrl": True, "repeat": True},
     {"properties":
      [("type", 'PANRIGHT'),
       ],
      },
     ),
    ("view3d.view_pan",
     {"type": 'NUMPAD_4', "value": 'PRESS', "ctrl": True, "repeat": True},
     {"properties":
      [("type", 'PANUP'),
       ],
      },
     ),
    ("view3d.view_roll",
     {"type": 'NUMPAD_4', "value": 'PRESS', "shift": True, "repeat": True},
     {"properties":
      [("type", 'LEFT'),
       ],
      },
     ),
    ("view3d.view_roll",
     {"type": 'NUMPAD_6', "value": 'PRESS', "shift": True, "repeat": True},
     {"properties":
      [("type", 'RIGHT'),
       ],
      },
     ),
    ("view3d.view_orbit",
     {"type": 'NUMPAD_9', "value": 'PRESS'},
     {"properties":
      [("angle", 3.1415927),
       ("type", 'ORBITRIGHT'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'EVT_TWEAK_M', "value": 'NORTH', "alt": True},
     {"properties":
      [("type", 'TOP'),
       ("relative", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'EVT_TWEAK_M', "value": 'SOUTH', "alt": True},
     {"properties":
      [("type", 'BOTTOM'),
       ("relative", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'EVT_TWEAK_M', "value": 'EAST', "alt": True},
     {"properties":
      [("type", 'RIGHT'),
       ("relative", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'EVT_TWEAK_M', "value": 'WEST', "alt": True},
     {"properties":
      [("type", 'LEFT'),
       ("relative", True),
       ],
      },
     ),
    ("view3d.view_center_pick", {"type": 'MIDDLEMOUSE', "value": 'CLICK', "alt": True}, None),
    ("view3d.ndof_orbit_zoom", {"type": 'NDOF_MOTION', "value": 'ANY'}, None),
    ("view3d.ndof_orbit", {"type": 'NDOF_MOTION', "value": 'ANY', "ctrl": True}, None),
    ("view3d.ndof_pan", {"type": 'NDOF_MOTION', "value": 'ANY', "shift": True}, None),
    ("view3d.ndof_all", {"type": 'NDOF_MOTION', "value": 'ANY', "shift": True, "ctrl": True}, None),
    ("view3d.view_selected",
     {"type": 'T', "value": 'PRESS', "shift": True, "ctrl": True, "alt": True},
     {"properties":
      [("use_all_regions", False),
       ],
      },
     ),
    ("view3d.view_roll",
     {"type": 'NDOF_BUTTON_ROLL_CCW', "value": 'PRESS'},
     {"properties":
      [("type", 'LEFT'),
       ],
      },
     ),
    ("view3d.view_roll",
     {"type": 'NDOF_BUTTON_ROLL_CCW', "value": 'PRESS'},
     {"properties":
      [("type", 'RIGHT'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NDOF_BUTTON_FRONT', "value": 'PRESS'},
     {"properties":
      [("type", 'FRONT'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NDOF_BUTTON_BACK', "value": 'PRESS'},
     {"properties":
      [("type", 'BACK'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NDOF_BUTTON_LEFT', "value": 'PRESS'},
     {"properties":
      [("type", 'LEFT'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NDOF_BUTTON_RIGHT', "value": 'PRESS'},
     {"properties":
      [("type", 'RIGHT'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NDOF_BUTTON_TOP', "value": 'PRESS'},
     {"properties":
      [("type", 'TOP'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NDOF_BUTTON_BOTTOM', "value": 'PRESS'},
     {"properties":
      [("type", 'BOTTOM'),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NDOF_BUTTON_FRONT', "value": 'PRESS', "shift": True},
     {"properties":
      [("type", 'FRONT'),
       ("align_active", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NDOF_BUTTON_RIGHT', "value": 'PRESS', "shift": True},
     {"properties":
      [("type", 'RIGHT'),
       ("align_active", True),
       ],
      },
     ),
    ("view3d.view_axis",
     {"type": 'NDOF_BUTTON_TOP', "value": 'PRESS', "shift": True},
     {"properties":
      [("type", 'TOP'),
       ("align_active", True),
       ],
      },
     ),
    ("view3d.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK'},
     {"properties":
      [("deselect_all", True),
       ],
      },
     ),
    ("view3d.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True},
     {"properties":
      [("toggle", True),
       ],
      },
     ),
    ("view3d.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "ctrl": True},
     {"properties":
      [("center", True),
       ("object", True),
       ],
      },
     ),
    ("view3d.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "alt": True},
     {"properties":
      [("enumerate", True),
       ],
      },
     ),
    ("view3d.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True, "ctrl": True},
     {"properties":
      [("toggle", True),
       ("center", True),
       ],
      },
     ),
    ("view3d.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "ctrl": True, "alt": True},
     {"properties":
      [("center", True),
       ("enumerate", True),
       ],
      },
     ),
    ("view3d.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True, "alt": True},
     {"properties":
      [("toggle", True),
       ("enumerate", True),
       ],
      },
     ),
    ("view3d.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True, "ctrl": True, "alt": True},
     {"properties":
      [("toggle", True),
       ("center", True),
       ("enumerate", True),
       ],
      },
     ),
    ("view3d.select_box", {"type": 'B', "value": 'PRESS'}, None),
    ("view3d.select_lasso",
     {"type": 'EVT_TWEAK_R', "value": 'ANY', "ctrl": True},
     {"properties":
      [("mode", 'ADD'),
       ],
      },
     ),
    ("view3d.select_lasso",
     {"type": 'EVT_TWEAK_R', "value": 'ANY', "shift": True, "ctrl": True},
     {"properties":
      [("mode", 'SUB'),
       ],
      },
     ),
    ("view3d.select_circle", {"type": 'C', "value": 'PRESS'}, None),
    ("view3d.clip_border", {"type": 'B', "value": 'PRESS', "alt": True}, None),
    ("view3d.zoom_border", {"type": 'B', "value": 'PRESS', "shift": True}, None),
    ("view3d.render_border", {"type": 'B', "value": 'PRESS', "ctrl": True}, None),
    ("view3d.clear_render_border", {"type": 'B', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("view3d.camera_to_view", {"type": 'NUMPAD_0', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("view3d.object_as_camera", {"type": 'NUMPAD_0', "value": 'PRESS', "ctrl": True}, None),
    ("view3d.copybuffer", {"type": 'C', "value": 'PRESS', "ctrl": True}, None),
    ("view3d.pastebuffer", {"type": 'V', "value": 'PRESS', "ctrl": True}, None),
    ("transform.translate", {"type": 'G', "value": 'PRESS'}, None),
    ("transform.translate", {"type": 'EVT_TWEAK_L', "value": 'ANY'}, None),
    ("transform.rotate", {"type": 'R', "value": 'PRESS'}, None),
    ("transform.resize", {"type": 'S', "value": 'PRESS'}, None),
    ("transform.bend", {"type": 'W', "value": 'PRESS', "shift": True}, None),
    ("transform.tosphere", {"type": 'S', "value": 'PRESS', "shift": True, "alt": True}, None),
    ("transform.shear", {"type": 'S', "value": 'PRESS', "shift": True, "ctrl": True, "alt": True}, None),
    ("transform.mirror", {"type": 'M', "value": 'PRESS', "ctrl": True}, None),
    ("object.transform_axis_target", {"type": 'T', "value": 'PRESS', "shift": True}, None),
    ("transform.skin_resize", {"type": 'A', "value": 'PRESS', "ctrl": True}, None),
    ("wm.context_toggle",
     {"type": 'TAB', "value": 'PRESS', "shift": True},
     {"properties":
      [("data_path", 'tool_settings.use_snap'),
       ],
      },
     ),
    ("wm.call_panel",
     {"type": 'TAB', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("name", 'VIEW3D_PT_snapping'),
       ("keep_open", True),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'S', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'VIEW3D_MT_snap_pie'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'ACCENT_GRAVE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("data_path", 'space_data.show_gizmo'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'PERIOD', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_pivot_pie'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'COMMA', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_orientations_pie'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'Z', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_shading_pie'),
       ],
      },
     ),
    ("view3d.toggle_shading",
     {"type": 'Z', "value": 'PRESS', "shift": True},
     {"properties":
      [("type", 'WIREFRAME'),
       ],
      },
     ),
    ("view3d.toggle_xray", {"type": 'Z', "value": 'PRESS', "alt": True}, None),
    ("wm.context_toggle",
     {"type": 'Z', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("data_path", 'space_data.overlay.show_overlays'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'W', "value": 'PRESS'},
     {"properties":
      [("name", 'builtin.select_box'),
       ("cycle", True),
       ],
      },
     ),
    ],
   },
  ),
 ("Frames",
  {"space_type": 'EMPTY', "region_type": 'WINDOW'},
  {"items":
   [("screen.frame_offset",
     {"type": 'LEFT_ARROW', "value": 'PRESS', "repeat": True},
     {"properties":
      [("delta", -1),
       ],
      },
     ),
    ("screen.frame_offset",
     {"type": 'RIGHT_ARROW', "value": 'PRESS', "repeat": True},
     {"properties":
      [("delta", 1),
       ],
      },
     ),
    ("screen.frame_jump",
     {"type": 'RIGHT_ARROW', "value": 'PRESS', "shift": True, "repeat": True},
     {"properties":
      [("end", True),
       ],
      },
     ),
    ("screen.frame_jump",
     {"type": 'LEFT_ARROW', "value": 'PRESS', "shift": True, "repeat": True},
     {"properties":
      [("end", False),
       ],
      },
     ),
    ("screen.keyframe_jump",
     {"type": 'UP_ARROW', "value": 'PRESS', "repeat": True},
     {"properties":
      [("next", True),
       ],
      },
     ),
    ("screen.keyframe_jump",
     {"type": 'DOWN_ARROW', "value": 'PRESS', "repeat": True},
     {"properties":
      [("next", False),
       ],
      },
     ),
    ("screen.keyframe_jump",
     {"type": 'MEDIA_LAST', "value": 'PRESS'},
     {"properties":
      [("next", True),
       ],
      },
     ),
    ("screen.keyframe_jump",
     {"type": 'MEDIA_FIRST', "value": 'PRESS'},
     {"properties":
      [("next", False),
       ],
      },
     ),
    ("screen.frame_offset",
     {"type": 'WHEELDOWNMOUSE', "value": 'PRESS', "alt": True},
     {"properties":
      [("delta", 1),
       ],
      },
     ),
    ("screen.frame_offset",
     {"type": 'WHEELUPMOUSE', "value": 'PRESS', "alt": True},
     {"properties":
      [("delta", -1),
       ],
      },
     ),
    ("screen.animation_cancel", {"type": 'ESC', "value": 'PRESS'}, None),
    ("screen.animation_cancel", {"type": 'MEDIA_STOP', "value": 'PRESS'}, None),
    ],
   },
  ),
 ("Grease Pencil Stroke Edit Mode",
  {"space_type": 'EMPTY', "region_type": 'WINDOW'},
  {"items":
   [("gpencil.interpolate", {"type": 'E', "value": 'PRESS', "ctrl": True}, None),
    ("gpencil.interpolate_sequence", {"type": 'E', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("gpencil.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK'},
     {"properties":
      [("deselect_all", True),
       ],
      },
     ),
    ("gpencil.select_all",
     {"type": 'A', "value": 'PRESS'},
     {"properties":
      [("action", 'SELECT'),
       ],
      },
     ),
    ("gpencil.select_all",
     {"type": 'A', "value": 'PRESS', "alt": True},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("gpencil.select_all",
     {"type": 'I', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("action", 'INVERT'),
       ],
      },
     ),
    ("gpencil.select_all",
     {"type": 'A', "value": 'DOUBLE_CLICK'},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("gpencil.select_circle", {"type": 'C', "value": 'PRESS'}, None),
    ("gpencil.select_box", {"type": 'B', "value": 'PRESS'}, None),
    ("gpencil.select_lasso",
     {"type": 'EVT_TWEAK_R', "value": 'ANY', "ctrl": True},
     {"properties":
      [("mode", 'ADD'),
       ],
      },
     ),
    ("gpencil.select_lasso",
     {"type": 'EVT_TWEAK_R', "value": 'ANY', "shift": True, "ctrl": True},
     {"properties":
      [("mode", 'SUB'),
       ],
      },
     ),
    ("gpencil.select_lasso",
     {"type": 'EVT_TWEAK_R', "value": 'ANY', "ctrl": True, "alt": True},
     {"properties":
      [("mode", 'ADD'),
       ],
      },
     ),
    ("gpencil.select_lasso",
     {"type": 'EVT_TWEAK_R', "value": 'ANY', "shift": True, "ctrl": True, "alt": True},
     {"properties":
      [("mode", 'SUB'),
       ],
      },
     ),
    ("gpencil.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True},
     {"properties":
      [("extend", True),
       ("toggle", True),
       ],
      },
     ),
    ("gpencil.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "alt": True},
     {"properties":
      [("entire_strokes", True),
       ],
      },
     ),
    ("gpencil.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True, "alt": True},
     {"properties":
      [("extend", True),
       ("entire_strokes", True),
       ],
      },
     ),
    ("gpencil.select_linked", {"type": 'L', "value": 'PRESS'}, None),
    ("gpencil.select_linked", {"type": 'L', "value": 'PRESS', "ctrl": True}, None),
    ("gpencil.select_alternate", {"type": 'L', "value": 'PRESS', "shift": True}, None),
    ("gpencil.select_grouped", {"type": 'G', "value": 'PRESS', "shift": True}, None),
    ("gpencil.select_more", {"type": 'NUMPAD_PLUS', "value": 'PRESS', "ctrl": True, "repeat": True}, None),
    ("gpencil.select_less", {"type": 'NUMPAD_MINUS', "value": 'PRESS', "ctrl": True, "repeat": True}, None),
    ("gpencil.duplicate_move", {"type": 'D', "value": 'PRESS', "shift": True}, None),
    ("gpencil.extrude_move", {"type": 'E', "value": 'PRESS'}, None),
    ("wm.call_menu",
     {"type": 'X', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_edit_gpencil_delete'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'DEL', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_edit_gpencil_delete'),
       ],
      },
     ),
    ("gpencil.dissolve", {"type": 'X', "value": 'PRESS', "ctrl": True}, None),
    ("gpencil.dissolve", {"type": 'DEL', "value": 'PRESS', "ctrl": True}, None),
    ("gpencil.blank_frame_add", {"type": 'I', "value": 'PRESS', "shift": True}, None),
    ("gpencil.active_frames_delete_all", {"type": 'X', "value": 'PRESS', "shift": True}, None),
    ("gpencil.active_frames_delete_all", {"type": 'DEL', "value": 'PRESS', "shift": True}, None),
    ("gpencil.stroke_separate", {"type": 'P', "value": 'PRESS'}, None),
    ("gpencil.stroke_split", {"type": 'V', "value": 'PRESS'}, None),
    ("gpencil.stroke_join", {"type": 'J', "value": 'PRESS', "ctrl": True}, None),
    ("gpencil.stroke_join",
     {"type": 'J', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("type", 'JOINCOPY'),
       ],
      },
     ),
    ("gpencil.stroke_cyclical_set",
     {"type": 'F', "value": 'PRESS'},
     {"properties":
      [("type", 'CLOSE'),
       ("geometry", True),
       ],
      },
     ),
    ("gpencil.copy", {"type": 'C', "value": 'PRESS', "ctrl": True}, None),
    ("gpencil.paste", {"type": 'V', "value": 'PRESS', "ctrl": True}, None),
    ("wm.call_menu_pie",
     {"type": 'S', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'GPENCIL_MT_snap_pie'),
       ],
      },
     ),
    ("gpencil.reveal", {"type": 'H', "value": 'PRESS', "alt": True}, None),
    ("gpencil.hide",
     {"type": 'H', "value": 'PRESS'},
     {"properties":
      [("unselected", False),
       ],
      },
     ),
    ("gpencil.hide",
     {"type": 'H', "value": 'PRESS', "shift": True},
     {"properties":
      [("unselected", True),
       ],
      },
     ),
    ("gpencil.selection_opacity_toggle", {"type": 'H', "value": 'PRESS', "ctrl": True}, None),
    ("wm.context_toggle",
     {"type": 'Q', "value": 'PRESS', "shift": True},
     {"properties":
      [("data_path", 'space_data.overlay.use_gpencil_edit_lines'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'Q', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("data_path", 'space_data.overlay.use_gpencil_multiedit_line_only'),
       ],
      },
     ),
    ("gpencil.layer_isolate", {"type": 'NUMPAD_ASTERIX', "value": 'PRESS'}, None),
    ("wm.call_menu",
     {"type": 'M', "value": 'PRESS'},
     {"properties":
      [("name", 'GPENCIL_MT_move_to_layer'),
       ],
      },
     ),
    ("transform.translate", {"type": 'G', "value": 'PRESS'}, None),
    ("transform.translate", {"type": 'EVT_TWEAK_L', "value": 'ANY'}, None),
    ("transform.rotate", {"type": 'R', "value": 'PRESS'}, None),
    ("transform.resize", {"type": 'S', "value": 'PRESS'}, None),
    ("transform.mirror", {"type": 'M', "value": 'PRESS', "ctrl": True}, None),
    ("transform.bend", {"type": 'W', "value": 'PRESS', "shift": True}, None),
    ("transform.tosphere", {"type": 'S', "value": 'PRESS', "shift": True, "alt": True}, None),
    ("transform.shear", {"type": 'S', "value": 'PRESS', "shift": True, "ctrl": True, "alt": True}, None),
    ("transform.transform",
     {"type": 'S', "value": 'PRESS', "alt": True},
     {"properties":
      [("mode", 'GPENCIL_SHRINKFATTEN'),
       ],
      },
     ),
    ("transform.transform",
     {"type": 'F', "value": 'PRESS', "shift": True},
     {"properties":
      [("mode", 'GPENCIL_OPACITY'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'O', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'VIEW3D_MT_proportional_editing_falloff_pie'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'O', "value": 'PRESS'},
     {"properties":
      [("data_path", 'tool_settings.use_proportional_edit'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'O', "value": 'PRESS', "alt": True},
     {"properties":
      [("data_path", 'tool_settings.use_proportional_connected'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'U', "value": 'PRESS'},
     {"properties":
      [("data_path", 'gpencil_data.use_curve_edit'),
       ],
      },
     ),
    ("object.gpencil_add", {"type": 'A', "value": 'PRESS', "shift": True}, None),
    ("wm.call_menu",
     {"type": 'G', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'GPENCIL_MT_gpencil_vertex_group'),
       ],
      },
     ),
    ("gpencil.selectmode_toggle",
     {"type": 'ONE', "value": 'PRESS'},
     {"properties":
      [("mode", 0),
       ],
      },
     ),
    ("gpencil.selectmode_toggle",
     {"type": 'TWO', "value": 'PRESS'},
     {"properties":
      [("mode", 1),
       ],
      },
     ),
    ("gpencil.selectmode_toggle",
     {"type": 'THREE', "value": 'PRESS'},
     {"properties":
      [("mode", 2),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'Y', "value": 'PRESS'},
     {"properties":
      [("name", 'GPENCIL_MT_layer_active'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'RIGHTMOUSE', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_gpencil_edit_context_menu'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'APP', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_gpencil_edit_context_menu'),
       ],
      },
     ),
    ],
   },
  ),
 ("Grease Pencil Stroke Paint Mode",
  {"space_type": 'EMPTY', "region_type": 'WINDOW'},
  {"items":
   [("wm.radial_control",
     {"type": 'F', "value": 'PRESS', "shift": True},
     {"properties":
      [("data_path_primary", 'tool_settings.gpencil_paint.brush.gpencil_settings.pen_strength'),
       ],
      },
     ),
    ("wm.radial_control",
     {"type": 'F', "value": 'PRESS'},
     {"properties":
      [("data_path_primary", 'tool_settings.gpencil_paint.brush.size'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'X', "value": 'PRESS'},
     {"properties":
      [("name", 'GPENCIL_MT_gpencil_draw_delete'),
       ],
      },
     ),
    ("gpencil.blank_frame_add", {"type": 'I', "value": 'PRESS', "shift": True}, None),
    ("gpencil.active_frames_delete_all", {"type": 'X', "value": 'PRESS', "shift": True}, None),
    ("gpencil.active_frames_delete_all", {"type": 'DEL', "value": 'PRESS', "shift": True}, None),
    ("gpencil.interpolate", {"type": 'E', "value": 'PRESS', "ctrl": True}, None),
    ("gpencil.interpolate_sequence", {"type": 'E', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("gpencil.reveal", {"type": 'H', "value": 'PRESS', "alt": True}, None),
    ("gpencil.hide",
     {"type": 'H', "value": 'PRESS'},
     {"properties":
      [("unselected", False),
       ],
      },
     ),
    ("gpencil.hide",
     {"type": 'H', "value": 'PRESS', "shift": True},
     {"properties":
      [("unselected", True),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'Y', "value": 'PRESS'},
     {"properties":
      [("name", 'GPENCIL_MT_layer_active'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'U', "value": 'PRESS'},
     {"properties":
      [("name", 'GPENCIL_MT_material_active'),
       ],
      },
     ),
    ("wm.call_panel",
     {"type": 'RIGHTMOUSE', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_PT_gpencil_draw_context_menu'),
       ],
      },
     ),
    ("wm.call_panel",
     {"type": 'APP', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_PT_gpencil_draw_context_menu'),
       ],
      },
     ),
    ],
   },
  ),
 ("Grease Pencil Stroke Sculpt Mode",
  {"space_type": 'EMPTY', "region_type": 'WINDOW'},
  {"items":
   [("gpencil.select_all",
     {"type": 'A', "value": 'PRESS'},
     {"properties":
      [("action", 'SELECT'),
       ],
      },
     ),
    ("gpencil.select_all",
     {"type": 'A', "value": 'PRESS', "alt": True},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("gpencil.select_all",
     {"type": 'I', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("action", 'INVERT'),
       ],
      },
     ),
    ("gpencil.select_all",
     {"type": 'A', "value": 'DOUBLE_CLICK'},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("gpencil.select_circle", {"type": 'C', "value": 'PRESS'}, None),
    ("gpencil.select_box", {"type": 'B', "value": 'PRESS'}, None),
    ("gpencil.select_lasso",
     {"type": 'EVT_TWEAK_R', "value": 'ANY', "ctrl": True},
     {"properties":
      [("mode", 'ADD'),
       ],
      },
     ),
    ("gpencil.select_lasso",
     {"type": 'EVT_TWEAK_R', "value": 'ANY', "shift": True, "ctrl": True},
     {"properties":
      [("mode", 'SUB'),
       ],
      },
     ),
    ("gpencil.select_lasso",
     {"type": 'EVT_TWEAK_R', "value": 'ANY', "ctrl": True, "alt": True},
     {"properties":
      [("mode", 'ADD'),
       ],
      },
     ),
    ("gpencil.select_lasso",
     {"type": 'EVT_TWEAK_R', "value": 'ANY', "shift": True, "ctrl": True, "alt": True},
     {"properties":
      [("mode", 'SUB'),
       ],
      },
     ),
    ("gpencil.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True},
     {"properties":
      [("extend", True),
       ("toggle", True),
       ],
      },
     ),
    ("gpencil.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "alt": True},
     {"properties":
      [("entire_strokes", True),
       ],
      },
     ),
    ("gpencil.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True, "alt": True},
     {"properties":
      [("extend", True),
       ("entire_strokes", True),
       ],
      },
     ),
    ("gpencil.select_linked", {"type": 'L', "value": 'PRESS'}, None),
    ("gpencil.select_linked", {"type": 'L', "value": 'PRESS', "ctrl": True}, None),
    ("gpencil.select_alternate", {"type": 'L', "value": 'PRESS', "shift": True}, None),
    ("gpencil.select_grouped", {"type": 'G', "value": 'PRESS', "shift": True}, None),
    ("gpencil.select_more", {"type": 'NUMPAD_PLUS', "value": 'PRESS', "ctrl": True, "repeat": True}, None),
    ("gpencil.select_less", {"type": 'NUMPAD_MINUS', "value": 'PRESS', "ctrl": True, "repeat": True}, None),
    ("wm.radial_control",
     {"type": 'F', "value": 'PRESS', "shift": True},
     {"properties":
      [("data_path_primary", 'tool_settings.gpencil_sculpt_paint.brush.strength'),
       ],
      },
     ),
    ("wm.radial_control",
     {"type": 'F', "value": 'PRESS'},
     {"properties":
      [("data_path_primary", 'tool_settings.gpencil_sculpt_paint.brush.size'),
       ],
      },
     ),
    ("gpencil.copy", {"type": 'C', "value": 'PRESS', "ctrl": True}, None),
    ("wm.context_toggle",
     {"type": 'Q', "value": 'PRESS', "shift": True},
     {"properties":
      [("data_path", 'space_data.overlay.use_gpencil_edit_lines'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'Q', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("data_path", 'space_data.overlay.use_gpencil_multiedit_line_only'),
       ],
      },
     ),
    ("gpencil.blank_frame_add", {"type": 'I', "value": 'PRESS', "shift": True}, None),
    ("gpencil.active_frames_delete_all", {"type": 'X', "value": 'PRESS', "shift": True}, None),
    ("gpencil.active_frames_delete_all", {"type": 'DEL', "value": 'PRESS', "shift": True}, None),
    ("wm.call_menu",
     {"type": 'Y', "value": 'PRESS'},
     {"properties":
      [("name", 'GPENCIL_MT_layer_active'),
       ],
      },
     ),
    ("wm.call_panel",
     {"type": 'RIGHTMOUSE', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_PT_gpencil_sculpt_context_menu'),
       ],
      },
     ),
    ("wm.call_panel",
     {"type": 'APP', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_PT_gpencil_sculpt_context_menu'),
       ],
      },
     ),
    ],
   },
  ),
 ("Grease Pencil Stroke Vertex Mode",
  {"space_type": 'EMPTY', "region_type": 'WINDOW'},
  {"items":
   [("gpencil.select_all",
     {"type": 'A', "value": 'PRESS'},
     {"properties":
      [("action", 'SELECT'),
       ],
      },
     ),
    ("gpencil.select_all",
     {"type": 'A', "value": 'PRESS', "alt": True},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("gpencil.select_all",
     {"type": 'I', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("action", 'INVERT'),
       ],
      },
     ),
    ("gpencil.select_all",
     {"type": 'A', "value": 'DOUBLE_CLICK'},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("gpencil.select_circle", {"type": 'C', "value": 'PRESS'}, None),
    ("gpencil.select_box", {"type": 'B', "value": 'PRESS'}, None),
    ("gpencil.select_lasso",
     {"type": 'EVT_TWEAK_R', "value": 'ANY', "ctrl": True},
     {"properties":
      [("mode", 'ADD'),
       ],
      },
     ),
    ("gpencil.select_lasso",
     {"type": 'EVT_TWEAK_R', "value": 'ANY', "shift": True, "ctrl": True},
     {"properties":
      [("mode", 'SUB'),
       ],
      },
     ),
    ("gpencil.select_lasso",
     {"type": 'EVT_TWEAK_R', "value": 'ANY', "ctrl": True, "alt": True},
     {"properties":
      [("mode", 'ADD'),
       ],
      },
     ),
    ("gpencil.select_lasso",
     {"type": 'EVT_TWEAK_R', "value": 'ANY', "shift": True, "ctrl": True, "alt": True},
     {"properties":
      [("mode", 'SUB'),
       ],
      },
     ),
    ("gpencil.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True},
     {"properties":
      [("extend", True),
       ("toggle", True),
       ],
      },
     ),
    ("gpencil.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "alt": True},
     {"properties":
      [("entire_strokes", True),
       ],
      },
     ),
    ("gpencil.select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True, "alt": True},
     {"properties":
      [("extend", True),
       ("entire_strokes", True),
       ],
      },
     ),
    ("gpencil.select_linked", {"type": 'L', "value": 'PRESS'}, None),
    ("gpencil.select_linked", {"type": 'L', "value": 'PRESS', "ctrl": True}, None),
    ("gpencil.select_alternate", {"type": 'L', "value": 'PRESS', "shift": True}, None),
    ("gpencil.select_grouped", {"type": 'G', "value": 'PRESS', "shift": True}, None),
    ("gpencil.select_more", {"type": 'NUMPAD_PLUS', "value": 'PRESS', "ctrl": True, "repeat": True}, None),
    ("gpencil.select_less", {"type": 'NUMPAD_MINUS', "value": 'PRESS', "ctrl": True, "repeat": True}, None),
    ("wm.radial_control",
     {"type": 'F', "value": 'PRESS', "shift": True},
     {"properties":
      [("data_path_primary", 'tool_settings.gpencil_vertex_paint.brush.gpencil_settings.pen_strength'),
       ],
      },
     ),
    ("wm.radial_control",
     {"type": 'F', "value": 'PRESS'},
     {"properties":
      [("data_path_primary", 'tool_settings.gpencil_vertex_paint.brush.size'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'Q', "value": 'PRESS', "shift": True},
     {"properties":
      [("data_path", 'space_data.overlay.use_gpencil_edit_lines'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'Q', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("data_path", 'space_data.overlay.use_gpencil_multiedit_line_only'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'D', "value": 'PRESS'},
     {"properties":
      [("name", 'builtin_brush.Draw'),
       ],
      },
     ),
    ("gpencil.blank_frame_add", {"type": 'I', "value": 'PRESS', "shift": True}, None),
    ("gpencil.active_frames_delete_all", {"type": 'X', "value": 'PRESS', "shift": True}, None),
    ("gpencil.active_frames_delete_all", {"type": 'DEL', "value": 'PRESS', "shift": True}, None),
    ("wm.call_menu",
     {"type": 'Y', "value": 'PRESS'},
     {"properties":
      [("name", 'GPENCIL_MT_layer_active'),
       ],
      },
     ),
    ("wm.call_panel",
     {"type": 'RIGHTMOUSE', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_PT_gpencil_vertex_context_menu'),
       ],
      },
     ),
    ],
   },
  ),
 ("Grease Pencil Stroke Weight Mode",
  {"space_type": 'EMPTY', "region_type": 'WINDOW'},
  {"items":
   [("wm.radial_control",
     {"type": 'F', "value": 'PRESS', "shift": True},
     {"properties":
      [("data_path_primary", 'tool_settings.gpencil_weight_paint.brush.strength'),
       ],
      },
     ),
    ("wm.radial_control",
     {"type": 'F', "value": 'PRESS'},
     {"properties":
      [("data_path_primary", 'tool_settings.gpencil_weight_paint.brush.size'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'Q', "value": 'PRESS', "shift": True},
     {"properties":
      [("data_path", 'space_data.overlay.use_gpencil_edit_lines'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'Q', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("data_path", 'space_data.overlay.use_gpencil_multiedit_line_only'),
       ],
      },
     ),
    ("gpencil.blank_frame_add", {"type": 'I', "value": 'PRESS', "shift": True}, None),
    ("gpencil.active_frames_delete_all", {"type": 'X', "value": 'PRESS', "shift": True}, None),
    ("gpencil.active_frames_delete_all", {"type": 'DEL', "value": 'PRESS', "shift": True}, None),
    ("wm.call_menu",
     {"type": 'Y', "value": 'PRESS'},
     {"properties":
      [("name", 'GPENCIL_MT_layer_active'),
       ],
      },
     ),
    ("wm.call_panel",
     {"type": 'RIGHTMOUSE', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_PT_gpencil_weight_context_menu'),
       ],
      },
     ),
    ("wm.call_panel",
     {"type": 'APP', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_PT_gpencil_weight_context_menu'),
       ],
      },
     ),
    ("view3d.select", {"type": 'LEFTMOUSE', "value": 'PRESS', "ctrl": True}, None),
    ],
   },
  ),
 ("Mesh",
  {"space_type": 'EMPTY', "region_type": 'WINDOW'},
  {"items":
   [("hops.edit_bool_difference", {"type": 'NUMPAD_MINUS', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("hops.edit_bool_union", {"type": 'NUMPAD_PLUS', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("machin3.symmetrize",
     {"type": 'Z', "value": 'PRESS', "alt": True},
     {"properties":
      [("axis", 'Z'),
       ("direction", 'POSITIVE'),
       ],
      },
     ),
    ("machin3.symmetrize",
     {"type": 'Y', "value": 'PRESS', "alt": True},
     {"properties":
      [("axis", 'Y'),
       ("direction", 'NEGATIVE'),
       ],
      },
     ),
    ("machin3.symmetrize",
     {"type": 'X', "value": 'PRESS', "alt": True},
     {"properties":
      [("axis", 'X'),
       ("direction", 'POSITIVE'),
       ],
      },
     ),
    ("machin3.call_mesh_machine_menu",
     {"type": 'Y', "value": 'PRESS'},
     {"properties":
      [("idname", 'mesh_machine'),
       ],
      },
     ),
    ("hops.edit_bool_difference", {"type": 'NUMPAD_MINUS', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("hops.edit_bool_union", {"type": 'NUMPAD_PLUS', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("machin3.symmetrize",
     {"type": 'Z', "value": 'PRESS', "alt": True},
     {"properties":
      [("axis", 'Z'),
       ("direction", 'POSITIVE'),
       ],
      },
     ),
    ("machin3.symmetrize",
     {"type": 'Y', "value": 'PRESS', "alt": True},
     {"properties":
      [("axis", 'Y'),
       ("direction", 'NEGATIVE'),
       ],
      },
     ),
    ("machin3.symmetrize",
     {"type": 'X', "value": 'PRESS', "alt": True},
     {"properties":
      [("axis", 'X'),
       ("direction", 'POSITIVE'),
       ],
      },
     ),
    ("machin3.call_mesh_machine_menu",
     {"type": 'Y', "value": 'PRESS'},
     {"properties":
      [("idname", 'mesh_machine'),
       ],
      },
     ),
    ("object.switch_object", {"type": 'D', "value": 'RELEASE'}, None),
    ("mesh.loopcut_slide",
     {"type": 'R', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("TRANSFORM_OT_edge_slide",
        [("release_confirm", False),
         ],
        ),
       ],
      },
     ),
    ("mesh.offset_edge_loops_slide",
     {"type": 'R', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("TRANSFORM_OT_edge_slide",
        [("release_confirm", False),
         ],
        ),
       ],
      },
     ),
    ("mesh.inset", {"type": 'I', "value": 'PRESS'}, None),
    ("mesh.bevel",
     {"type": 'B', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("affect", 'EDGES'),
       ],
      },
     ),
    ("mesh.bevel",
     {"type": 'B', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("affect", 'VERTICES'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'NUMPAD_1', "value": 'PRESS', "shift": True},
     {"properties":
      [("type", 'VERT'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'NUMPAD_2', "value": 'PRESS', "shift": True},
     {"properties":
      [("type", 'EDGE'),
       ],
      },
     ),
    ("mesh.select_mode",
     {"type": 'NUMPAD_3', "value": 'PRESS', "shift": True},
     {"properties":
      [("type", 'FACE'),
       ],
      },
     ),
    ("mesh.loop_select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "alt": True},
     {"properties":
      [("extend", False),
       ("deselect", False),
       ("toggle", False),
       ],
      },
     ),
    ("mesh.loop_select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True, "alt": True},
     {"properties":
      [("extend", False),
       ("deselect", False),
       ("toggle", True),
       ],
      },
     ),
    ("mesh.edgering_select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "ctrl": True, "alt": True},
     {"properties":
      [("extend", False),
       ("deselect", False),
       ("toggle", False),
       ],
      },
     ),
    ("mesh.edgering_select",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True, "ctrl": True, "alt": True},
     {"properties":
      [("extend", False),
       ("deselect", False),
       ("toggle", True),
       ],
      },
     ),
    ("mesh.shortest_path_pick",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "ctrl": True},
     {"properties":
      [("use_fill", False),
       ],
      },
     ),
    ("mesh.shortest_path_pick",
     {"type": 'LEFTMOUSE', "value": 'CLICK', "shift": True, "ctrl": True},
     {"properties":
      [("use_fill", True),
       ],
      },
     ),
    ("mesh.select_all",
     {"type": 'A', "value": 'PRESS'},
     {"properties":
      [("action", 'SELECT'),
       ],
      },
     ),
    ("mesh.select_all",
     {"type": 'A', "value": 'PRESS', "alt": True},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("mesh.select_all",
     {"type": 'I', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("action", 'INVERT'),
       ],
      },
     ),
    ("mesh.select_all",
     {"type": 'A', "value": 'DOUBLE_CLICK'},
     {"properties":
      [("action", 'DESELECT'),
       ],
      },
     ),
    ("mesh.select_more", {"type": 'NUMPAD_PLUS', "value": 'PRESS', "ctrl": True, "repeat": True}, None),
    ("mesh.select_less", {"type": 'NUMPAD_MINUS', "value": 'PRESS', "ctrl": True, "repeat": True}, None),
    ("mesh.select_next_item", {"type": 'NUMPAD_PLUS', "value": 'PRESS', "shift": True, "ctrl": True, "repeat": True}, None),
    ("mesh.select_prev_item", {"type": 'NUMPAD_MINUS', "value": 'PRESS', "shift": True, "ctrl": True, "repeat": True}, None),
    ("mesh.select_linked", {"type": 'L', "value": 'PRESS', "ctrl": True}, None),
    ("mesh.select_linked_pick",
     {"type": 'L', "value": 'PRESS'},
     {"properties":
      [("deselect", False),
       ],
      },
     ),
    ("mesh.select_linked_pick",
     {"type": 'L', "value": 'PRESS', "shift": True},
     {"properties":
      [("deselect", True),
       ],
      },
     ),
    ("mesh.select_mirror", {"type": 'M', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("wm.call_menu",
     {"type": 'G', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_select_similar'),
       ],
      },
     ),
    ("mesh.hide",
     {"type": 'H', "value": 'PRESS'},
     {"properties":
      [("unselected", False),
       ],
      },
     ),
    ("mesh.hide",
     {"type": 'H', "value": 'PRESS', "shift": True},
     {"properties":
      [("unselected", True),
       ],
      },
     ),
    ("mesh.reveal", {"type": 'H', "value": 'PRESS', "alt": True}, None),
    ("mesh.normals_make_consistent",
     {"type": 'N', "value": 'PRESS', "shift": True},
     {"properties":
      [("inside", False),
       ],
      },
     ),
    ("mesh.normals_make_consistent",
     {"type": 'N', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("inside", True),
       ],
      },
     ),
    ("view3d.edit_mesh_extrude_move_normal", {"type": 'E', "value": 'PRESS'}, None),
    ("wm.call_menu",
     {"type": 'E', "value": 'PRESS', "alt": True},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_extrude'),
       ],
      },
     ),
    ("transform.edge_crease", {"type": 'E', "value": 'PRESS', "shift": True}, None),
    ("mesh.fill", {"type": 'F', "value": 'PRESS', "alt": True}, None),
    ("mesh.quads_convert_to_tris",
     {"type": 'T', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("quad_method", 'BEAUTY'),
       ("ngon_method", 'BEAUTY'),
       ],
      },
     ),
    ("mesh.quads_convert_to_tris",
     {"type": 'T', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("quad_method", 'FIXED'),
       ("ngon_method", 'CLIP'),
       ],
      },
     ),
    ("mesh.tris_convert_to_quads", {"type": 'J', "value": 'PRESS', "alt": True}, None),
    ("mesh.rip_move",
     {"type": 'V', "value": 'PRESS'},
     {"properties":
      [("MESH_OT_rip",
        [("use_fill", False),
         ],
        ),
       ],
      },
     ),
    ("mesh.rip_move",
     {"type": 'V', "value": 'PRESS', "alt": True},
     {"properties":
      [("MESH_OT_rip",
        [("use_fill", True),
         ],
        ),
       ],
      },
     ),
    ("mesh.rip_edge_move", {"type": 'D', "value": 'PRESS', "alt": True}, None),
    ("wm.call_menu",
     {"type": 'M', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_merge'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'M', "value": 'PRESS', "alt": True},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_split'),
       ],
      },
     ),
    ("transform.shrink_fatten", {"type": 'S', "value": 'PRESS', "alt": True}, None),
    ("mesh.edge_face_add", {"type": 'F', "value": 'PRESS', "repeat": True}, None),
    ("mesh.duplicate_move", {"type": 'D', "value": 'PRESS', "shift": True}, None),
    ("wm.call_menu",
     {"type": 'A', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'VIEW3D_MT_mesh_add'),
       ],
      },
     ),
    ("mesh.separate", {"type": 'P', "value": 'PRESS'}, None),
    ("mesh.split", {"type": 'Y', "value": 'PRESS'}, None),
    ("mesh.vert_connect_path", {"type": 'J', "value": 'PRESS'}, None),
    ("mesh.point_normals", {"type": 'L', "value": 'PRESS', "alt": True}, None),
    ("transform.vert_slide", {"type": 'V', "value": 'PRESS', "shift": True}, None),
    ("mesh.dupli_extrude_cursor",
     {"type": 'RIGHTMOUSE', "value": 'CLICK', "ctrl": True},
     {"properties":
      [("rotate_source", True),
       ],
      },
     ),
    ("mesh.dupli_extrude_cursor",
     {"type": 'RIGHTMOUSE', "value": 'CLICK', "shift": True, "ctrl": True},
     {"properties":
      [("rotate_source", False),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'X', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_delete'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'DEL', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_delete'),
       ],
      },
     ),
    ("mesh.dissolve_mode", {"type": 'X', "value": 'PRESS', "ctrl": True}, None),
    ("mesh.dissolve_mode", {"type": 'DEL', "value": 'PRESS', "ctrl": True}, None),
    ("mesh.knife_tool",
     {"type": 'K', "value": 'PRESS'},
     {"properties":
      [("use_occlude_geometry", True),
       ("only_selected", False),
       ],
      },
     ),
    ("mesh.knife_tool",
     {"type": 'K', "value": 'PRESS', "shift": True},
     {"properties":
      [("use_occlude_geometry", False),
       ("only_selected", True),
       ],
      },
     ),
    ("object.vertex_parent_set", {"type": 'P', "value": 'PRESS', "ctrl": True}, None),
    ("wm.call_menu",
     {"type": 'F', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_faces'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'E', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_edges'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'V', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_vertices'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'H', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'VIEW3D_MT_hook'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'U', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_uv_map'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'G', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'VIEW3D_MT_vertex_group'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'N', "value": 'PRESS', "alt": True},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_normals'),
       ],
      },
     ),
    ("object.vertex_group_remove_from", {"type": 'G', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("wm.call_menu_pie",
     {"type": 'O', "value": 'PRESS', "shift": True},
     {"properties":
      [("name", 'VIEW3D_MT_proportional_editing_falloff_pie'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'O', "value": 'PRESS'},
     {"properties":
      [("data_path", 'tool_settings.use_proportional_edit'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'O', "value": 'PRESS', "alt": True},
     {"properties":
      [("data_path", 'tool_settings.use_proportional_connected'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'RIGHTMOUSE', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_context_menu'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'APP', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_edit_mesh_context_menu'),
       ],
      },
     ),
    ],
   },
  ),
 ("Sculpt",
  {"space_type": 'EMPTY', "region_type": 'WINDOW'},
  {"items":
   [("sculpt.wheel", {"type": 'SPACE', "value": 'PRESS'}, None),
    ("object.switch_object", {"type": 'D', "value": 'RELEASE'}, None),
    ("sculpt.brush_stroke",
     {"type": 'LEFTMOUSE', "value": 'PRESS'},
     {"properties":
      [("mode", 'NORMAL'),
       ],
      },
     ),
    ("sculpt.brush_stroke",
     {"type": 'LEFTMOUSE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("mode", 'INVERT'),
       ],
      },
     ),
    ("sculpt.brush_stroke",
     {"type": 'LEFTMOUSE', "value": 'PRESS', "shift": True},
     {"properties":
      [("mode", 'SMOOTH'),
       ],
      },
     ),
    ("sculpt.face_set_change_visibility",
     {"type": 'H', "value": 'PRESS'},
     {"properties":
      [("mode", 'TOGGLE'),
       ],
      },
     ),
    ("sculpt.face_set_change_visibility",
     {"type": 'H', "value": 'PRESS', "shift": True},
     {"properties":
      [("mode", 'HIDE_ACTIVE'),
       ],
      },
     ),
    ("sculpt.face_set_change_visibility",
     {"type": 'H', "value": 'PRESS', "alt": True},
     {"properties":
      [("mode", 'SHOW_ALL'),
       ],
      },
     ),
    ("sculpt.mask_expand",
     {"type": 'W', "value": 'PRESS', "shift": True},
     {"properties":
      [("invert", False),
       ("smooth_iterations", 0),
       ("use_normals", False),
       ("keep_previous_mask", False),
       ("create_face_set", True),
       ],
      },
     ),
    ("sculpt.face_set_edit",
     {"type": 'W', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("mode", 'GROW'),
       ],
      },
     ),
    ("sculpt.face_set_edit",
     {"type": 'W', "value": 'PRESS', "ctrl": True, "alt": True},
     {"properties":
      [("mode", 'SHRINK'),
       ],
      },
     ),
    ("object.subdivision_set",
     {"type": 'ZERO', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("level", 0),
       ("relative", False),
       ],
      },
     ),
    ("object.subdivision_set",
     {"type": 'ONE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("level", 1),
       ("relative", False),
       ],
      },
     ),
    ("object.subdivision_set",
     {"type": 'TWO', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("level", 2),
       ("relative", False),
       ],
      },
     ),
    ("object.subdivision_set",
     {"type": 'THREE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("level", 3),
       ("relative", False),
       ],
      },
     ),
    ("object.subdivision_set",
     {"type": 'FOUR', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("level", 4),
       ("relative", False),
       ],
      },
     ),
    ("object.subdivision_set",
     {"type": 'FIVE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("level", 5),
       ("relative", False),
       ],
      },
     ),
    ("object.subdivision_set",
     {"type": 'PAGE_UP', "value": 'PRESS', "repeat": True},
     {"properties":
      [("level", 1),
       ("relative", True),
       ],
      },
     ),
    ("object.subdivision_set",
     {"type": 'PAGE_DOWN', "value": 'PRESS', "repeat": True},
     {"properties":
      [("level", -1),
       ("relative", True),
       ],
      },
     ),
    ("paint.mask_flood_fill",
     {"type": 'M', "value": 'PRESS', "alt": True},
     {"properties":
      [("mode", 'VALUE'),
       ("value", 0.0),
       ],
      },
     ),
    ("paint.mask_flood_fill",
     {"type": 'I', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("mode", 'INVERT'),
       ],
      },
     ),
    ("paint.mask_box_gesture",
     {"type": 'B', "value": 'PRESS'},
     {"properties":
      [("mode", 'VALUE'),
       ("value", 0.0),
       ],
      },
     ),
    ("paint.mask_lasso_gesture", {"type": 'LEFTMOUSE', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("wm.context_toggle",
     {"type": 'M', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("data_path", 'scene.tool_settings.sculpt.show_mask'),
       ],
      },
     ),
    ("sculpt.mask_expand",
     {"type": 'A', "value": 'PRESS', "shift": True},
     {"properties":
      [("invert", True),
       ("smooth_iterations", 2),
       ("use_normals", False),
       ("keep_previous_mask", False),
       ("create_face_set", False),
       ],
      },
     ),
    ("sculpt.mask_expand",
     {"type": 'A', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("invert", False),
       ("smooth_iterations", 0),
       ("use_normals", True),
       ("keep_previous_mask", True),
       ("create_face_set", False),
       ],
      },
     ),
    ("sculpt.dynamic_topology_toggle", {"type": 'D', "value": 'PRESS', "ctrl": True}, None),
    ("sculpt.dyntopo_detail_size_edit", {"type": 'D', "value": 'PRESS', "shift": True}, None),
    ("object.voxel_remesh", {"type": 'R', "value": 'PRESS', "ctrl": True}, None),
    ("object.voxel_size_edit", {"type": 'R', "value": 'PRESS', "shift": True}, None),
    ("object.quadriflow_remesh", {"type": 'R', "value": 'PRESS', "ctrl": True, "alt": True}, None),
    ("sculpt.sample_color", {"type": 'S', "value": 'PRESS'}, None),
    ("brush.scale_size",
     {"type": 'LEFT_BRACKET', "value": 'PRESS', "repeat": True},
     {"properties":
      [("scalar", 0.9),
       ],
      },
     ),
    ("brush.scale_size",
     {"type": 'RIGHT_BRACKET', "value": 'PRESS', "repeat": True},
     {"properties":
      [("scalar", 1.1111112),
       ],
      },
     ),
    ("wm.radial_control",
     {"type": 'F', "value": 'PRESS'},
     {"properties":
      [("data_path_primary", 'tool_settings.sculpt.brush.size'),
       ("data_path_secondary", 'tool_settings.unified_paint_settings.size'),
       ("use_secondary", 'tool_settings.unified_paint_settings.use_unified_size'),
       ("rotation_path", 'tool_settings.sculpt.brush.texture_slot.angle'),
       ("color_path", 'tool_settings.sculpt.brush.cursor_color_add'),
       ("fill_color_path", ''),
       ("fill_color_override_path", ''),
       ("fill_color_override_test_path", ''),
       ("zoom_path", ''),
       ("image_id", 'tool_settings.sculpt.brush'),
       ("secondary_tex", False),
       ],
      },
     ),
    ("wm.radial_control",
     {"type": 'F', "value": 'PRESS', "shift": True},
     {"properties":
      [("data_path_primary", 'tool_settings.sculpt.brush.strength'),
       ("data_path_secondary", 'tool_settings.unified_paint_settings.strength'),
       ("use_secondary", 'tool_settings.unified_paint_settings.use_unified_strength'),
       ("rotation_path", 'tool_settings.sculpt.brush.texture_slot.angle'),
       ("color_path", 'tool_settings.sculpt.brush.cursor_color_add'),
       ("fill_color_path", ''),
       ("fill_color_override_path", ''),
       ("fill_color_override_test_path", ''),
       ("zoom_path", ''),
       ("image_id", 'tool_settings.sculpt.brush'),
       ("secondary_tex", False),
       ],
      },
     ),
    ("wm.radial_control",
     {"type": 'F', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("data_path_primary", 'tool_settings.sculpt.brush.texture_slot.angle'),
       ("data_path_secondary", ''),
       ("use_secondary", ''),
       ("rotation_path", 'tool_settings.sculpt.brush.texture_slot.angle'),
       ("color_path", 'tool_settings.sculpt.brush.cursor_color_add'),
       ("fill_color_path", ''),
       ("fill_color_override_path", ''),
       ("fill_color_override_test_path", ''),
       ("zoom_path", ''),
       ("image_id", 'tool_settings.sculpt.brush'),
       ("secondary_tex", False),
       ],
      },
     ),
    ("brush.stencil_control",
     {"type": 'RIGHTMOUSE', "value": 'PRESS'},
     {"properties":
      [("mode", 'TRANSLATION'),
       ],
      },
     ),
    ("brush.stencil_control",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "shift": True},
     {"properties":
      [("mode", 'SCALE'),
       ],
      },
     ),
    ("brush.stencil_control",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("mode", 'ROTATION'),
       ],
      },
     ),
    ("brush.stencil_control",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "alt": True},
     {"properties":
      [("mode", 'TRANSLATION'),
       ("texmode", 'SECONDARY'),
       ],
      },
     ),
    ("brush.stencil_control",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "shift": True, "alt": True},
     {"properties":
      [("mode", 'SCALE'),
       ("texmode", 'SECONDARY'),
       ],
      },
     ),
    ("brush.stencil_control",
     {"type": 'RIGHTMOUSE', "value": 'PRESS', "ctrl": True, "alt": True},
     {"properties":
      [("mode", 'ROTATION'),
       ("texmode", 'SECONDARY'),
       ],
      },
     ),
    ("paint.brush_select",
     {"type": 'X', "value": 'PRESS'},
     {"properties":
      [("sculpt_tool", 'DRAW'),
       ],
      },
     ),
    ("paint.brush_select",
     {"type": 'S', "value": 'PRESS', "shift": True},
     {"properties":
      [("sculpt_tool", 'SMOOTH'),
       ],
      },
     ),
    ("paint.brush_select",
     {"type": 'P', "value": 'PRESS'},
     {"properties":
      [("sculpt_tool", 'PINCH'),
       ],
      },
     ),
    ("paint.brush_select",
     {"type": 'I', "value": 'PRESS'},
     {"properties":
      [("sculpt_tool", 'INFLATE'),
       ],
      },
     ),
    ("paint.brush_select",
     {"type": 'G', "value": 'PRESS'},
     {"properties":
      [("sculpt_tool", 'GRAB'),
       ],
      },
     ),
    ("paint.brush_select",
     {"type": 'L', "value": 'PRESS'},
     {"properties":
      [("sculpt_tool", 'LAYER'),
       ],
      },
     ),
    ("paint.brush_select",
     {"type": 'T', "value": 'PRESS', "shift": True},
     {"properties":
      [("sculpt_tool", 'FLATTEN'),
       ],
      },
     ),
    ("paint.brush_select",
     {"type": 'C', "value": 'PRESS'},
     {"properties":
      [("sculpt_tool", 'CLAY'),
       ],
      },
     ),
    ("paint.brush_select",
     {"type": 'C', "value": 'PRESS', "shift": True},
     {"properties":
      [("sculpt_tool", 'CREASE'),
       ],
      },
     ),
    ("paint.brush_select",
     {"type": 'K', "value": 'PRESS'},
     {"properties":
      [("sculpt_tool", 'SNAKE_HOOK'),
       ],
      },
     ),
    ("paint.brush_select",
     {"type": 'M', "value": 'PRESS'},
     {"properties":
      [("sculpt_tool", 'MASK'),
       ("toggle", True),
       ("create_missing", True),
       ],
      },
     ),
    ("wm.context_menu_enum",
     {"type": 'E', "value": 'PRESS'},
     {"properties":
      [("data_path", 'tool_settings.sculpt.brush.stroke_method'),
       ],
      },
     ),
    ("wm.context_toggle",
     {"type": 'S', "value": 'PRESS', "shift": True},
     {"properties":
      [("data_path", 'tool_settings.sculpt.brush.use_smooth_stroke'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'R', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_angle_control'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'A', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_sculpt_mask_edit_pie'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'A', "value": 'PRESS', "alt": True},
     {"properties":
      [("name", 'VIEW3D_MT_sculpt_automasking_pie'),
       ],
      },
     ),
    ("wm.call_menu_pie",
     {"type": 'W', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_MT_sculpt_face_sets_edit_pie'),
       ],
      },
     ),
    ("wm.call_panel",
     {"type": 'RIGHTMOUSE', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_PT_sculpt_context_menu'),
       ],
      },
     ),
    ("wm.call_panel",
     {"type": 'APP', "value": 'PRESS'},
     {"properties":
      [("name", 'VIEW3D_PT_sculpt_context_menu'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'NUMPAD_4', "value": 'PRESS', "repeat": True},
     {"properties":
      [("name", 'builtin_brush.Draw'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'NUMPAD_5', "value": 'PRESS', "repeat": True},
     {"properties":
      [("name", 'builtin_brush.Clay Strips'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'NUMPAD_6', "value": 'PRESS', "repeat": True},
     {"properties":
      [("name", 'builtin_brush.Inflate'),
       ],
      },
     ),
    ("wm.tool_set_by_id",
     {"type": 'NUMPAD_7', "value": 'PRESS', "repeat": True},
     {"properties":
      [("name", 'builtin_brush.Grab'),
       ],
      },
     ),
    ],
   },
  ),
 ("Window",
  {"space_type": 'EMPTY', "region_type": 'WINDOW'},
  {"items":
   [("wm.blenderkit_fast_metadata", {"type": 'F', "value": 'PRESS', "ctrl": True}, None),
    ("wm.blenderkit_menu_rating_upload", {"type": 'F', "value": 'PRESS'}, None),
    ("view3d.blenderkit_asset_bar",
     {"type": 'SEMI_COLON', "value": 'PRESS'},
     {"properties":
      [("do_search", False),
       ("keep_running", False),
       ],
      },
     ),
    ("wm.blenderkit_fast_metadata", {"type": 'F', "value": 'PRESS', "ctrl": True}, None),
    ("wm.blenderkit_menu_rating_upload", {"type": 'F', "value": 'PRESS'}, None),
    ("view3d.blenderkit_asset_bar",
     {"type": 'SEMI_COLON', "value": 'PRESS'},
     {"properties":
      [("do_search", False),
       ("keep_running", False),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'N', "value": 'PRESS', "ctrl": True},
     {"properties":
      [("name", 'TOPBAR_MT_file_new'),
       ],
      },
     ),
    ("wm.call_menu",
     {"type": 'O', "value": 'PRESS', "shift": True, "ctrl": True},
     {"properties":
      [("name", 'TOPBAR_MT_file_open_recent'),
       ],
      },
     ),
    ("wm.open_mainfile", {"type": 'O', "value": 'PRESS', "ctrl": True}, None),
    ("wm.save_mainfile", {"type": 'S', "value": 'PRESS', "ctrl": True}, None),
    ("wm.save_as_mainfile", {"type": 'S', "value": 'PRESS', "shift": True, "ctrl": True}, None),
    ("wm.quit_blender", {"type": 'Q', "value": 'PRESS', "ctrl": True}, None),
    ("wm.call_menu",
     {"type": 'BUTTON4MOUSE', "value": 'PRESS'},
     {"properties":
      [("name", 'SCREEN_MT_user_menu'),
       ],
      },
     ),
    ("screen.space_type_set_or_cycle",
     {"type": 'F1', "value": 'PRESS', "shift": True},
     {"properties":
      [("space_type", 'FILE_BROWSER'),
       ],
      },
     ),
    ("screen.space_type_set_or_cycle",
     {"type": 'F2', "value": 'PRESS', "shift": True},
     {"properties":
      [("space_type", 'CLIP_EDITOR'),
       ],
      },
     ),
    ("screen.space_type_set_or_cycle",
     {"type": 'F3', "value": 'PRESS', "shift": True},
     {"properties":
      [("space_type", 'NODE_EDITOR'),
       ],
      },
     ),
    ("screen.space_type_set_or_cycle",
     {"type": 'F4', "value": 'PRESS', "shift": True},
     {"properties":
      [("space_type", 'CONSOLE'),
       ],
      },
     ),
    ("screen.space_type_set_or_cycle",
     {"type": 'F5', "value": 'PRESS', "shift": True},
     {"properties":
      [("space_type", 'VIEW_3D'),
       ],
      },
     ),
    ("screen.space_type_set_or_cycle",
     {"type": 'F6', "value": 'PRESS', "shift": True},
     {"properties":
      [("space_type", 'GRAPH_EDITOR'),
       ],
      },
     ),
    ("screen.space_type_set_or_cycle",
     {"type": 'F7', "value": 'PRESS', "shift": True},
     {"properties":
      [("space_type", 'PROPERTIES'),
       ],
      },
     ),
    ("screen.space_type_set_or_cycle",
     {"type": 'F8', "value": 'PRESS', "shift": True},
     {"properties":
      [("space_type", 'SEQUENCE_EDITOR'),
       ],
      },
     ),
    ("screen.space_type_set_or_cycle",
     {"type": 'F9', "value": 'PRESS', "shift": True},
     {"properties":
      [("space_type", 'OUTLINER'),
       ],
      },
     ),
    ("screen.space_type_set_or_cycle",
     {"type": 'F10', "value": 'PRESS', "shift": True},
     {"properties":
      [("space_type", 'IMAGE_EDITOR'),
       ],
      },
     ),
    ("screen.space_type_set_or_cycle",
     {"type": 'F11', "value": 'PRESS', "shift": True},
     {"properties":
      [("space_type", 'TEXT_EDITOR'),
       ],
      },
     ),
    ("screen.space_type_set_or_cycle",
     {"type": 'F12', "value": 'PRESS', "shift": True},
     {"properties":
      [("space_type", 'DOPESHEET_EDITOR'),
       ],
      },
     ),
    ("wm.call_panel",
     {"type": 'NDOF_BUTTON_MENU', "value": 'PRESS'},
     {"properties":
      [("name", 'USERPREF_PT_ndof_settings'),
       ],
      },
     ),
    ("wm.context_scale_float",
     {"type": 'NDOF_BUTTON_PLUS', "value": 'PRESS'},
     {"properties":
      [("data_path", 'preferences.inputs.ndof_sensitivity'),
       ("value", 1.1),
       ],
      },
     ),
    ("wm.context_scale_float",
     {"type": 'NDOF_BUTTON_MINUS', "value": 'PRESS'},
     {"properties":
      [("data_path", 'preferences.inputs.ndof_sensitivity'),
       ("value", 0.90909094),
       ],
      },
     ),
    ("wm.context_scale_float",
     {"type": 'NDOF_BUTTON_PLUS', "value": 'PRESS', "shift": True},
     {"properties":
      [("data_path", 'preferences.inputs.ndof_sensitivity'),
       ("value", 1.5),
       ],
      },
     ),
    ("wm.context_scale_float",
     {"type": 'NDOF_BUTTON_MINUS', "value": 'PRESS', "shift": True},
     {"properties":
      [("data_path", 'preferences.inputs.ndof_sensitivity'),
       ("value", 0.6666667),
       ],
      },
     ),
    ("info.reports_display_update", {"type": 'TIMER_REPORT', "value": 'ANY', "any": True}, None),
    ("wm.doc_view_manual_ui_context", {"type": 'F1', "value": 'PRESS'}, None),
    ("wm.call_panel",
     {"type": 'F2', "value": 'PRESS'},
     {"properties":
      [("name", 'TOPBAR_PT_name'),
       ("keep_open", False),
       ],
      },
     ),
    ("wm.batch_rename", {"type": 'F2', "value": 'PRESS', "ctrl": True}, None),
    ("wm.search_menu", {"type": 'SPACE', "value": 'PRESS'}, None),
    ("wm.call_menu",
     {"type": 'F4', "value": 'PRESS'},
     {"properties":
      [("name", 'TOPBAR_MT_file_context_menu'),
       ],
      },
     ),
    ("wm.toolbar_fallback_pie", {"type": 'W', "value": 'PRESS', "alt": True}, None),
    ("wm.toolbar", {"type": 'SPACE', "value": 'PRESS', "shift": True}, None),
    ],
   },
  ),
 ]


if __name__ == "__main__":
    # Only add keywords that are supported.
    from bpy.app import version as blender_version
    keywords = {}
    if blender_version >= (2, 92, 0):
        keywords["keyconfig_version"] = keyconfig_version
    import os
    from bl_keymap_utils.io import keyconfig_import_from_data
    keyconfig_import_from_data(
        os.path.splitext(os.path.basename(__file__))[0],
        keyconfig_data,
        **keywords,
    )
